version: "3.9" # optional since v1.27.0

services:
  php-env:
    image: php:8.1.13-apache
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80

  MariaDB:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - MariaDB:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  MariaDB:
